name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Setup MelonLoader
      env:
        MELONLOADER_VERSION: v0.5.4
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./bootstrap-melonloader.ps1
      shell: pwsh

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal
